version: 0.2

phases:
  build:
    commands:
      #- echo "Updating Lambda function code..."
      #- aws lambda update-function-code --function-name nafees-test --publish --zip-file fileb://touseef-test.zip
      - echo "Creating Lambda function..."
      - aws lambda create-function --function-name MyLambdaFunction --runtime python3.8 --role arn:aws:iam::207496619564:policy/lambda-policy --handler lambda_function.lambda_handler --zip-file fileb://touseef-test.zip

      #- aws lambda create-function --function-name MyLambdaFunction --runtime nodejs14.x --role arn:aws:iam::aws:policy/AdministratorAccess --handler index.handler --zip-file fileb://touseef-test.zip

